# Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "setup.fullname" . }}-prometheus-grafana-datasource
  labels:
    grafana_datasource: '1'
{{ include "setup.labels" . | indent 4 }}
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://{{ .Release.Name }}-prometheus-server.{{ .Release.Namespace }}.svc.cluster.local